### PR TITLE
fix: stack overflow in KernelHost.run()

### LINKED ISSUE #778: Stack overflow in KernelHost.run()
### Affected Languages

- [X] `TypeScript` or `Javascript`
- [ ] `Python`
- [X] `Java`
- [ ] .NET (`C#`, `F#`, ...)

### General Information
* **JSII Version:** master
* **Platform:** OSX, Amazon Linux

### What is the problem?

I am getting a stack overflow error with large Java-based CDK CloudFormation stacks. This seems to be happening because the `KernelHost.run()` and `KernelHost.processRequest()` functions are mutually-recursive through the `next` callback.

```
RangeError: Maximum call stack size exceeded
    at KernelHost.processRequest (/tmp/jsii-java-runtime4513439031470941034/jsii-runtime.js:6063:18)
    at KernelHost.run (/tmp/jsii-java-runtime4513439031470941034/jsii-runtime.js:5970:14)
    at processRequest (/tmp/jsii-java-runtime4513439031470941034/jsii-runtime.js:5970:45)
    at KernelHost.processRequest (/tmp/jsii-java-runtime4513439031470941034/jsii-runtime.js:6066:16)
    at KernelHost.run (/tmp/jsii-java-runtime4513439031470941034/jsii-runtime.js:5970:14)
    at processRequest (/tmp/jsii-java-runtime4513439031470941034/jsii-runtime.js:5970:45)
    at KernelHost.processRequest (/tmp/jsii-java-runtime4513439031470941034/jsii-runtime.js:6066:16)
    at KernelHost.run (/tmp/jsii-java-runtime4513439031470941034/jsii-runtime.js:5970:14)
    at processRequest (/tmp/jsii-java-runtime4513439031470941034/jsii-runtime.js:5970:45)
    at KernelHost.processRequest (/tmp/jsii-java-runtime4513439031470941034/jsii-runtime.js:6066:16)
    at software.amazon.jsii.JsiiRuntime.processErrorResponse(JsiiRuntime.java:112)
    at software.amazon.jsii.JsiiRuntime.requestResponse(JsiiRuntime.java:84)
    at software.amazon.jsii.JsiiClient.callMethod(JsiiClient.java:185)
    at software.amazon.jsii.JsiiObject.jsiiCall(JsiiObject.java:57)
    [our stack...]
```

I will submit a PR with a test and fix shortly.

### PR DESCRIPTION
**Pull request by ddinu**
Fixes #778. This PR eliminates the mutual recursion between `KernelHost.run()` and `KernelHost.processRequest()` by scheduling the recursive `KernelHost.run()` call to run on the next iteration of the event loop.

The code change has been tested as follows:

- by running the stress-test script with and without the change to confirm that the crash occurs without the change and does not occur with the change;
- by running the unit tests to confirm that behavior is consistent;
- by synthesizing our internal CDK stack and confirming that the crash does not occur and that resources are generated correctly.

---

By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license].

[Apache 2.0 license]: https://www.apache.org/licenses/LICENSE-2.0

### CODE REVIEW

**Comment by ddinu** [comment]
I have updated the description. Please let me know if anything else is needed.

File: packages/jsii-runtime/lib/host.ts [hunk 1]
```diff
@@ -14,7 +14,7 @@ export class KernelHost {
             return; // done
         }
 
-        this.processRequest(req, () => this.run());
+        this.processRequest(req, () => setImmediate(() => this.run()));
```
Comment (eladb) [inline packages/jsii-runtime/lib/host.ts]: I wonder if this should be inside processRequest
Also add a comment explaining why this is needed

Comment (ddinu) [reply packages/jsii-runtime/lib/host.ts]: I wasn't sure whether it belongs inside run() or processRequest(). I went with this because it seemed to be less invasive:

The result of the next() call is returned from processRequest(), and this wouldn't be possible with a setImmediate() call.  This would affect callbackHandler()/completeCallback() because it returns processRequest()'s result. Limiting the change to run() doesn't affect anything because run() discards processRequest()'s result.

Is that too cautious?

If the behavior change is acceptable, then moving it to processRequest() would be nice.

Comment (eladb) [reply packages/jsii-runtime/lib/host.ts]: Got it. Let’s leave it like this. Just add some comments to explain why this is needed and we are golden.  Thanks for the quality contribution!

Comment (ddinu) [reply packages/jsii-runtime/lib/host.ts]: Thank you! I've added a comment.
