### PR TITLE
fix(java,dotnet): emit default implementations for optional properties

### LINKED ISSUE #543: Java - problems implementing class/interface with optional property
When implementing an `abstract class` or `interface` that defines optional properties, but not actually specifying the property (valid in TypeScript), the Java code generator will never emit the concrete implementation of the `get`ter, resulting in an invalid class.

### PR DESCRIPTION
**Pull request by RomainMuller**
For optional properties on interfaces, emit default implementations (for .NET,
this required upgrading the target to `netcoreapp3.0`) so that adding a new
optional property on an interface does not break existing code that implements
the interface.

In it's current form, the getters always return `null`, while the setters throw an
exception unless overridden.

Fixes #543

---

By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license].

[Apache 2.0 license]: https://www.apache.org/licenses/LICENSE-2.0

### CODE REVIEW

File: packages/jsii-pacmak/lib/targets/dotnet/filegenerator.ts [hunk 1]
```diff
@@ -50,7 +50,7 @@ export class FileGenerator {
     const rootNode = xmlbuilder.create('Project', { encoding: 'UTF-8', headless: true });
     rootNode.att('Sdk', 'Microsoft.NET.Sdk');
     const propertyGroup = rootNode.ele('PropertyGroup');
-    propertyGroup.ele('TargetFramework', 'netcoreapp2.1');
+    propertyGroup.ele('TargetFrameworks', 'netcoreapp2.1;netcoreapp3.0');
```
Comment (rix0rrr) [inline packages/jsii-pacmak/lib/targets/dotnet/filegenerator.ts]: Uh. Wut? The tag name changes?

File: packages/jsii-pacmak/test/diff-test.sh [hunk 2]
```diff
@@ -29,11 +29,6 @@ function assert-generator() {
         rsync -a ${original_expected}/ ${expected}/
     fi
 
-    if [[ -d ${original_expected}/java/target ]]; then
```
Comment (rix0rrr) [inline packages/jsii-pacmak/test/diff-test.sh]: This helps me a lot. Please don't remove it?

File: packages/jsii-pacmak/lib/targets/dotnet/filegenerator.ts (hunk 1 above)
Comment (RomainMuller) [reply packages/jsii-pacmak/lib/targets/dotnet/filegenerator.ts]: Yeah - there's a tag for singular target, and one for multi-targeting. Thank you (not) msbuild.

File: packages/jsii-pacmak/test/diff-test.sh (hunk 2 above)
Comment (RomainMuller) [reply packages/jsii-pacmak/test/diff-test.sh]: What problem does it solve? I had no problem after removing this... I'm curious what I'm missing!

It did however cause me **MUCH** pain, because my IDE just auto-touches stuff, and that made my iteration "edit code - close IDE - clean up files - test - open IDE - edit code - ...". This is painful.

File: packages/jsii-pacmak/lib/targets/dotnet/dotnetgenerator.ts [hunk 3]
```diff
@@ -183,10 +183,27 @@ export class DotNetGenerator extends Generator {
...
 
+    if (prop.optional) {
+      // Conditional compilation - default interface implementation requires C#8.0 support, which imples netcoreapp3.0 or above!
+      this.code.line('#if NETCOREAPP3_0');
+      this.code.openBlock('get');
+      this.code.line('return null;');
+      this.code.closeBlock();
+      if (!prop.immutable) {
+        this.code.openBlock('set');
+        this.code.line(`throw new System.NotSupportedException("'set' for '${propName}' is not implemented");`);
```
[the remark this answers is not in the document]
Comment (RomainMuller) [reply packages/jsii-pacmak/lib/targets/dotnet/dotnetgenerator.ts]: The issue here is that interfaces cannot declare properties, and if I want to "store" values here, I have to have the default implementation use some external storage (maybe a static data store class somewhere). This is one thing I had considered by it feels fairly ugly...

What do you think about the addition of an `@Optional` annotation to denote those methods that you need to "opt into" manually?

[the remark this answers is not in the document]
Comment (rix0rrr) [reply packages/jsii-pacmak/lib/targets/dotnet/dotnetgenerator.ts]: Well I was going to suggest that, but turns out this behavior actually correctly mimics TypeScript semantics. 

It was just surprising to me, so I suggest writing down somewhere that the current behavior is not only due to lack of other options, but even correct.

File: packages/jsii-pacmak/test/diff-test.sh (hunk 2 above)
Comment (rix0rrr) [reply packages/jsii-pacmak/test/diff-test.sh]: Yes, but for me NOT doing this check just leads to a more cryptic error downstream (you will see an error about the diff failing because one dir has target, .settings, .project).

I added a test explicitly to tell you WHY that was happening, because it was confusing to me.

If your IDE compiles the expectation dir, the test set will fail, regardless of whether this test is here or not.
