### PR TITLE
fix(pacmak): generated dependencies are not consistent with source npm module

### LINKED ISSUE #676: Python dependency versions not handled correctly
### Affected Languages

- [ ] `TypeScript` or `Javascript`
- [x] `Python`
- [ ] `Java`
- [ ] .NET (`C#`, `F#`, ...)

### General Information
* **JSII Version:** 0.14.3
* **Platform:**     MacOS

### What is the problem?

Transitive dependencies are not handled correctly in Python.  If you install version 1.2.0 (for example) of a CDK module, any transitive dependencies pull in the latest version and you get an incompatible set of modules.  This issue has also been reported in CDK as https://github.com/aws/aws-cdk/issues/3517

### PR DESCRIPTION
**Pull request by RomainMuller**
The dependency statements generated in the Java, .NET and Python
packages generated by `jsii-pacmak` were not reflecting the dependency
statement modeled on the source package. In certain pathological cases,
such as Python, the dependency declaration was often more permissive
than what the source package allowed, resulting in surprising behavior
as well as difficult to troubleshoot problems.

This updates several elements involved in this problem:
1. The `jsii` compiler no longer carries version information for
  transitive dependencies of the assembly in the `dependencyClosure`
  property, and instead only carries the `targets` configuration for
  those.
2. The version statements in the `dependencies` section of the `.jsii`
  file no longer contains the "compile-time resolved" version number,
  but the actual SemVer expression declared in the package's source.
  Also, the `targets` object was dropped (only the SemVer range
  statement remains), as this incurred needless duplication of the
  target configuration (in `dependencies` and `dependencyClosure`).
3. `jsii-pacmak` renders the declared SemVer range in the relevant form
  for the target being generated.

Fixes #676
Related to #1137

---

By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license].

[Apache 2.0 license]: https://www.apache.org/licenses/LICENSE-2.0

### CODE REVIEW

File: packages/@jsii/spec/lib/assembly.ts [hunk 1]
```diff
@@ -151,6 +145,19 @@ export interface Assembly extends Documentable {
...
+ * Shareable configuration of a jsii Assembly.
+ */
+export interface AssemblyConfiguration {
+  /**
+   * A map of target name to configuration, which is used when generating
+   * packages for various languages.
+   *
+   * @default none
+   */
+  targets?: AssemblyTargets;
```
[the remark this answers is not in the document]
Comment (rix0rrr) [reply packages/@jsii/spec/lib/assembly.ts]: And I wonder if embedding the "target" information of dependencies isn't going to lead to breakage at some point in the future. What if it changes? Should we not have a hash/check on it? If I change the namespace of a Java package, for example.

File: packages/jsii-pacmak/lib/targets/java.ts [hunk 2]
```diff
@@ -786,25 +786,74 @@ class JavaGenerator extends Generator {
...
 
+    /**
+     * Formats a SemVer version range into the equivalent Maven dependency notation.
+     *
+     * @see https://cwiki.apache.org/confluence/display/MAVENOLD/Dependency+Mediation+and+Conflict+Resolution
+     *
+     * @param version the semantic version number
+     * @param suffix a suffix to be appended to versions
+     */
+    function semverToMavenRange(version: string, suffix?: string): string {
```
Comment (rix0rrr) [inline packages/jsii-pacmak/lib/targets/java.ts]: Worth a couple of unit tests? Same for the other vdep wranglers.

File: packages/jsii/lib/assembler.ts [hunk 3]
```diff
@@ -1624,35 +1557,20 @@ function* intersect<T>(xs: Set<T>, ys: Set<T>) {
...
-  return Array.prototype.concat.call([], ...xs);
-}
-
 function noEmptyDict<T>(xs: {[key: string]: T}): {[key: string]: T} | undefined {
   if (Object.keys(xs).length === 0) { return undefined; }
   return xs;
 }
 
+function toDependencyClosure(assemblies: readonly spec.Assembly[]): { [name: string]: spec.AssemblyConfiguration } {
+  const result: { [name: string]: spec.AssemblyTargets } = {};
```
Comment (rix0rrr) [inline packages/jsii/lib/assembler.ts]: I see you got rid of the version conflict checkage. Are you sure it can't happen?

Comment (rix0rrr) [inline packages/jsii/lib/assembler.ts]: BTW, personally I find `Record<string, spec.AssemblyTargets>` easier on the eyes. This comment goes for all instances of `{ [key: string]: T}`.

File: packages/jsii-pacmak/lib/targets/python.ts [hunk 4]
```diff
@@ -1182,19 +1183,15 @@ class Package {
...
-      if (versionParts[0] === '0') {
-        versionSpecifier = `~=${versionParts.slice(0, 3).join('.')}`;
-      } else {
-        versionSpecifier = `~=${versionParts.slice(0, 2).join('.')},>=${versionParts.slice(0, 3).join('.')}`;
-      }
+    for (const [depName, version] of Object.entries(this.metadata.dependencies ?? {})) {
+      const depInfo = this.metadata.dependencyClosure![depName];
+
+      const range = new semver.Range(version);
+      const versionSpecifier = range.set.map(
```
Comment (rix0rrr) [inline packages/jsii-pacmak/lib/targets/python.ts]: Would be nice to put this in a function just like for the other languages, so it can be unit tested.

File: packages/jsii-pacmak/lib/targets/python.ts [hunk 5]
```diff
@@ -1182,19 +1183,15 @@ class Package {
...
+        set => set.map(
+          comp => `${comp.operator || '=='}${comp.semver.raw}`
```
Comment (rix0rrr) [inline packages/jsii-pacmak/lib/targets/python.ts]: What if `comp.operator` is equal to `"="`? Shouldn't it turn to `"=="` for pip?

What if `comp.operator` is equal to `"~"`? Shouldn't it turn to `"~="`?

File: packages/@jsii/spec/lib/assembly.ts (hunk 1 above)
[the remark this answers is not in the document]
Comment (RomainMuller) [reply packages/@jsii/spec/lib/assembly.ts]: That's be a breaking change and should be accompanied with a major version bump. However we currently have no validation for this.

File: packages/jsii-pacmak/lib/targets/python.ts (hunk 5 above)
Comment (RomainMuller) [reply packages/jsii-pacmak/lib/targets/python.ts]: Per the [type definitions](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/semver/index.d.ts#L275) `comp.operator` **cannot** be `~`. It however can be `=` in which case we'd actually render a single `=` which is no bueno. Good catch!

File: packages/jsii/lib/assembler.ts (hunk 3 above)
Comment (RomainMuller) [reply packages/jsii/lib/assembler.ts]: That's a very good point. I somehow though it was no longer necessary but that's not true. I'll update with a modified version where the "no conflict" check happens upfront (when loading the `ProjectInfo` object) and reduces the dependency statement to the intersection of all requirements found in the closure (which is the "most correct" way to go here, I feel, and will detect non-overlapping requirements at the same time)

Comment (RomainMuller) [reply packages/jsii/lib/assembler.ts]: I have mixed feelings here. I tend to agree but `Record<T>`  does not have a `readonly` form, whereas I can `{ readonly [name: string]: T }`, and I like the fact the syntax remains consistent. Decided not to change this time around (it felt like unnecessary churn), but probably will gradually adopt in the future in places where `readonly` is not useful.

File: packages/jsii-pacmak/test/targets/version-utils.test.ts [hunk 6]
```diff
@@ -0,0 +1,77 @@
+import { toMavenVersionRange, toNuGetVersionRange, toPythonVersionRange } from '../../lib/targets/version-utils';
+
+const examples: Record<string, { maven: string, nuget: string, python: string }> = {
```
Comment (rix0rrr) [inline packages/jsii-pacmak/test/targets/version-utils.test.ts]: Sweet, I like <3
