### PR TITLE
fix(kernel): tarball unpacking does not behave like 'npm install'

### LINKED ISSUE #1765: Kernel "load" results in surprising file permissions
### Affected Languages

- [ ] `TypeScript` or `Javascript`
- [X] `Python`
- [X] `Java`
- [X] .NET (`C#`, `F#`, ...)

### General Information
* **JSII Version:** *all existing versions*
* **Platform:**     *UNIX-like with a non-default `umask` such as `0027`*

### What is the problem?
Libraries loaded in the jsii kernel are not installed by `npm`, but directly unpacked. The `umask` is not overridden, leading to the current process configuration to be applied. This leads to installs that differ in file permissions from their `npm install`ed counterparts.

This has been found to cause aws/aws-cdk#8233

### PR DESCRIPTION
**Pull request by RomainMuller**
In it's wisdom, `npm install` does override the process' `umask` to
`0o022` before unpackging the tarball, to ensure the produced install
has the kind of permissions that one would expect, regardless of the
system-configured `umask`.

Because `@jsii/kernel` did not reproduce this behavior, loaded libraries
could be unpacked with unexpectedly tight permissions, leading to weird
issues when those files were used in contexts that required those
permissions. For example, this is the cause of aws/aws-cdk#8233.

Fixes #1765

---

By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license].

[Apache 2.0 license]: https://www.apache.org/licenses/LICENSE-2.0

### CODE REVIEW

File: packages/@jsii/kernel/lib/kernel.ts [hunk 1]
```diff
@@ -107,14 +107,23 @@ export class Kernel {
...
-      cwd: packageDir,
-      strip: 1, // Removes the 'package/' path element from entries
-      sync: true,
-    });
+
+    // Force umask to have npm-install-like permissions
+    const originalUmask = process.umask(0o022);
+    try {
+      // untar the archive to its final location
+      tar.extract({
```
Comment (eladb) [inline packages/@jsii/kernel/lib/kernel.ts:115]: You should use the built-in support in the [`tar`](https://www.npmjs.com/package/tar#tarcoptions-filelist-callback-alias-tarcreate) library.

One of these options should help:

* `portable` Omit metadata that is system-specific: ctime, atime, uid, gid, uname, gname, dev, ino, and nlink. Note that mtime is still included, because this is necessary for other time-based operations. Additionally, mode is set to a "reasonable default" for most unix systems, based on a umask value of 0o22.
* `mode` The mode to set on the created file archive

Comment (eladb) [reply packages/@jsii/kernel/lib/kernel.ts:115]: I feel `portable` is the right one to use here.

Comment (RomainMuller) [reply packages/@jsii/kernel/lib/kernel.ts:115]: Those options are specific to the `create` operation and this is the `extract` operation.

The only "built-in" option available is the `umask` option to `tar.extract`, however that is "internal" (and not exposed in the `d.ts` which is why I **decided** against using that).

Comment (eladb) [reply packages/@jsii/kernel/lib/kernel.ts:115]: Okay sorry my mistake.
