### PR TITLE
fix(pacmak): examples with multi-line strings produce invalid python docstrings

### LINKED ISSUE #2569: python: newlines in literal strings example code results in invalid syntax
### Affected Languages

- [ ] `TypeScript` or `Javascript`
- [x] `Python`
- [ ] `Java`
- [ ] .NET (`C#`, `F#`, ...)

### General Information
* **JSII Version:** 1.20.1

### What is the problem?

Consider the following jsii code:

```ts
/**
 * Hello world, this is cool.
 *
 * @example
 * const s1 = "\nFooBar";
 * const s2 = `Hello
 *   world!`;
 */
export class Hello {
  public sayHello() {
    return 'hello, world!';
  }
}
```

The generated python output looks like this:

```py
class Hello(metaclass=jsii.JSIIMeta, jsii_type="python-repro.Hello"):
    """Hello world, this is cool.

    Example::

        # Example automatically generated without compilation. See https://github.com/aws/jsii/issues/826
        s1 = """
        FooBar"""
        s2 = """Hello
          world!"""
    """

    def __init__(self) -> None:
        jsii.create(Hello, self, [])

    @jsii.member(jsii_name="sayHello")
    def say_hello(self) -> builtins.str:
        return typing.cast(builtins.str, jsii.invoke(self, "sayHello", []))
```

Notice that the `\n` in the example code was converted to `"""` pairs which should be escaped or just left as is since they are part of a string literal.

This was introduced in https://github.com/aws/jsii/pull/2419

### PR DESCRIPTION
**Pull request by eladb**
Since docstrings are now rendered inside single-quoted multiline strings to allow the docstring itself to include example code with double-quoted multiline string literals. Those are the ones produced by rosetta for python.

Fixes #2569

---

By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license].

[Apache 2.0 license]: https://www.apache.org/licenses/LICENSE-2.0

### CODE REVIEW

File: packages/jsii-pacmak/lib/targets/python.ts [hunk 1]
```diff
@@ -42,6 +42,10 @@ const requirementsFile = path.resolve(
   'requirements-dev.txt',
 );
 
+// we use single-quotes for multi-line strings to allow examples within the
+// docstrings themselves to include double-quotes (see https://github.com/aws/jsii/issues/2569)
```
Comment (RomainMuller) [inline packages/jsii-pacmak/lib/targets/python.ts:46]: That sounds very brittle to me... but okay...

**Review by RomainMuller — APPROVED** [review]

File: packages/jsii-pacmak/lib/targets/python.ts (hunk 1 above)
Comment (eladb) [reply packages/jsii-pacmak/lib/targets/python.ts:46]: I believe this is sufficient to fix this p0.
