### PR TITLE
fix(go): invalid generated code for classes a keyword name

### LINKED ISSUE #2637: go: invalid generated output for a class named `Default`
### Affected Languages

- [x] `Golang`
- [ ] `TypeScript` or `Javascript`
- [ ] `Python`
- [ ] `Java`
- [ ] .NET (`C#`, `F#`, ...)

### General Information
* **JSII Version:** 1.23.0
* **Platform:**     *any*

### What is the problem?

Consider the following jsii code:

```ts
export class Default {
  public sayHello() {
    return 'hello, world!';
  }
}
```

The output of `jsii-pacmak` is:

```
# godefault
./godefault.go:14:6: syntax error: unexpected default, expecting name
./godefault.go:20:7: syntax error: unexpected default, expecting expression
./godefault.go:22:2: syntax error: non-declaration statement outside function body
./godefault.go:32:10: syntax error: unexpected default, expecting type
```

### Verbose Log

The generated source looks like this:

`godefault.go`:

carbon-2

### PR DESCRIPTION
**Pull request by eladb**
Since these structs are all private, simply add a `_jsiiProxy` postfix to the name.

Fixes #2637

---

By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license].

[Apache 2.0 license]: https://www.apache.org/licenses/LICENSE-2.0

### CODE REVIEW

File: packages/jsii-pacmak/lib/targets/go/types/go-type.ts [hunk 1]
```diff
@@ -14,7 +14,9 @@ export abstract class GoType {
 
   public constructor(public pkg: Package, public type: Type) {
     this.name = toPascalCase(type.name);
-    this.proxyName = toCamelCase(type.name);
+    // add "_jsiiClass" postfix to private struct name to avoid keyword
+    // conflicts such as "default". see https://github.com/aws/jsii/issues/2637
+    this.proxyName = `${toCamelCase(type.name)}_jsiiClass`;
```
Comment (RomainMuller) [inline packages/jsii-pacmak/lib/targets/go/types/go-type.ts:19]: I'd name it `_jsiiProxy` instead of `_jsiiClass`, as this is super misleading when it actually is a jsii interface proxy type.

```suggestion
    // add "_jsiiProxy" postfix to private struct name to avoid keyword
    // conflicts such as "default". see https://github.com/aws/jsii/issues/2637
    this.proxyName = `${toCamelCase(type.name)}_jsiiProxy`;
```

**Review by RomainMuller — APPROVED** [review]
