### PR TITLE
fix(go): major version suffix is missing in module names for >=v2

### LINKED ISSUE #2509: go: local.go.sum is accidentally published
### Affected Languages

- [x] `golang`

### General Information
* **JSII Version:** 1.18.0
* **Platform:**     

### What is the problem?

The file `local.go.sum` should not be included in the published directory.

### PR DESCRIPTION
**Pull request by eladb**
According to the [go modules spec], starting from 2.0.0, module names must include
A “major version suffix” (e.g. `/v2`).

[go modules spec]: https://golang.org/ref/mod#major-version-suffixes

Fixes https://github.com/aws/jsii/issues/2506

This commit also fixes #2509 by deleting the `local.go.sum` file from the output.

---

By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license].

[Apache 2.0 license]: https://www.apache.org/licenses/LICENSE-2.0

### CODE REVIEW

File: packages/jsii-pacmak/lib/targets/go.ts [hunk 1]
```diff
@@ -229,3 +231,11 @@ async function go(command: string, args: string[], options: { cwd: string }) {
...
   return shell('go', [command, ...args], { cwd });
 }
+
+async function tryUnlink(filePath: string) {
+  if (!(await fs.pathExists(filePath))) {
+    return;
+  }
+
+  await fs.unlink(filePath);
+}
```
Comment (RomainMuller) [inline packages/jsii-pacmak/lib/targets/go.ts:241]: If we have `fs-extra` available, you could use `remove` from it instead of implementing this...

File: packages/jsii-pacmak/lib/targets/go/package.ts [hunk 2]
```diff
@@ -336,9 +340,26 @@ export class InternalPackage extends Package {
...
+      `Unable to parse version "${version}" as a semantic version`,
+    );
+  }
+
+  // suffix is only needed for 2.0 and above
+  if (sv.major <= 1) {
+    return '';
+  }
+
+  return `/v${sv.major.toString()}`;
```
Comment (RomainMuller) [inline packages/jsii-pacmak/lib/targets/go/package.ts:364]: I reckon the `.toString()` is not necessary here, since this is in a template expression (this will happen by default).

File: packages/jsii-pacmak/lib/targets/go/package.ts [hunk 3]
```diff
@@ -336,9 +340,26 @@ export class InternalPackage extends Package {
...
+
+function determineMajorVersionSuffix(version: string) {
+  const sv = semver.parse(version);
+  if (!sv) {
+    throw new Error(
+      `Unable to parse version "${version}" as a semantic version`,
+    );
+  }
+
+  // suffix is only needed for 2.0 and above
```
Comment (RomainMuller) [inline packages/jsii-pacmak/lib/targets/go/package.ts:359]: Can we get a link to the go documentation about this?

**Review by RomainMuller — COMMENTED** [review]
Mostly good, minor suggestions...

File: packages/jsii-pacmak/lib/targets/go.ts (hunk 1 above)
Comment (eladb) [reply packages/jsii-pacmak/lib/targets/go.ts:241]: Done.

File: packages/jsii-pacmak/lib/targets/go/package.ts (hunk 2 above)
Comment (eladb) [reply packages/jsii-pacmak/lib/targets/go/package.ts:364]: Done.

File: packages/jsii-pacmak/lib/targets/go/package.ts (hunk 3 above)
Comment (eladb) [reply packages/jsii-pacmak/lib/targets/go/package.ts:359]: Done

**Review by RomainMuller — APPROVED** [review]
