### PR TITLE
fix(rosetta): incorrect transliteration of map keys in python

### LINKED ISSUE #3448: CORS Error despite thoroughly reading CDK docs, CDK docs error in the public reference
### Affected Languages

- [ ] `TypeScript` or `Javascript`
- [ X] `Python`
- [ ] `Java`
- [ ] .NET (`C#`, `F#`, ...)
- [ ] `Go`

### General Information
* **JSII Version:** 
* **Platform:**     

### What is the problem?

The documentation about the AWS CDK for python when specifying the integration response, and method response wrongly put an extra under score on the "_access-_control-_allow-_origin", instead, the correct naming should be "Access-Control-Allow-Origin" which caused the customer's application not working even after throughly read the CDK docs.

I have attached the screen cap that customer shared with the ticket. The extra underscore could affect other parameter as well across the documentation.

### Verbose Log
[

### PR DESCRIPTION
**Pull request by RomainMuller**
The Python transliterator failed to properly account for maps when
transliterating keys, resulting in name-mangling being applied on these
when it should not have been.

This PR adds a new `inMap` context entry to track whether a property
assignment must be interpreted as a map key-value entry, or an actual
keyword/value mapping; and in that case circumvents the mangling.

Added a new test to verify that such map literals render appropriately
using a key similar to that which caused #3448.

Fixes #3448

---

By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license].

[Apache 2.0 license]: https://www.apache.org/licenses/LICENSE-2.0

### CODE REVIEW

File: packages/jsii-rosetta/lib/languages/python.ts [hunk 1]
```diff
@@ -608,19 +622,18 @@ export class PythonVisitor extends DefaultVisitor<PythonLanguageContext> {
     node: ts.StringLiteral | ts.NoSubstitutionTemplateLiteral,
     _context: PythonVisitorContext,
   ): OTree {
-    const rawText = node.text;
-    if (rawText.includes('\n')) {
+    if (node.getText(node.getSourceFile()).includes('\n')) {
```
Comment (madeline-k) [inline packages/jsii-rosetta/lib/languages/python.ts:625]: Whats this difference between this and node.text?

**Review by madeline-k — APPROVED** [review]

File: packages/jsii-rosetta/lib/languages/python.ts (hunk 1 above)
Comment (RomainMuller) [reply packages/jsii-rosetta/lib/languages/python.ts:625]: `node.text` is the JavaScript value of the string (in particular, with escape sequences replaced with their literal value, e.g: `\n` will be a "real" newline), whereas `node.getText()` will return the corresponding source code (which will have the escape sequences untouched).

The change here improves the situation a bit (avoid multi-lining literals that were not actually multi-line in the source), but it's also not perfect (probably good enough?) as it'll still cause some escapes to be replaced within multi-line literals).
