### PR TITLE
fix(java): correctly search for protected override implementations

### LINKED ISSUE #903: java: unable to override protected methods
### Affected Languages

- [ ] `TypeScript` or `Javascript`
- [ ] `Python`
- [x] `Java`
- [ ] .NET (`C#`, `F#`, ...)

### General Information
* **JSII Version:** 0.19.0
* **Platform:**   any  

### What is the problem?

When trying to override a protected jsii method in Java, the following error is printed:

```
software.amazon.jsii.JsiiException: Resolution error: Unable to find callback method with signature: protected java.lang.String com.amazon.noopf.tenantresourcegenrator.NoOpfStack.allocateLogicalId(software.amazon.awscdk.core.CfnElement).
```

An example would be to try and override the `allocateLogicalId` method in a subclass of `@aws-cdk/core.Stack`:

```java
public class MyStack extends Stack {
    private final String STACK_MAJOR_VERSION = "v1";

    public MyStack(App parent, String name, MyStackProps props) {
        super(parent, name, props);
        //CfnResource cfnResource = new CfnResource(...);
        //...
    }

    @Override
    protected String allocateLogicalId(CfnElement cfnElement) {
        return super.allocateLogicalId(cfnElement) + STACK_MAJOR_VERSION;
    }
}
```

### Workaround

A workaround (credits @RomainMuller) is to change the override from `protected` to `public`.

### PR DESCRIPTION
**Pull request by RomainMuller**
The code looking for overrides implementations was using the
`Class#getMethods` method, but this only considers `public` members of
the class. Chanegd to `#getDeclaredMethods` which accounts for *all* the
methods.

Fixes #903

---

By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license].

[Apache 2.0 license]: https://www.apache.org/licenses/LICENSE-2.0

### CODE REVIEW

File: packages/jsii-java-runtime-test/project/src/test/java/software/amazon/jsii/testing/ComplianceTest.java [hunk 1]
```diff
@@ -4,69 +4,14 @@
...
-import software.amazon.jsii.tests.calculator.ReturnsPrivateImplementationOfInterface;
-import software.amazon.jsii.tests.calculator.StableStruct;
-import software.amazon.jsii.tests.calculator.Statics;
-import software.amazon.jsii.tests.calculator.StructWithJavaReservedWords;
-import software.amazon.jsii.tests.calculator.Sum;
-import software.amazon.jsii.tests.calculator.SyncVirtualMethods;
-import software.amazon.jsii.tests.calculator.UnionProperties;
-import software.amazon.jsii.tests.calculator.UsesInterfaceWithProperties;
-import software.amazon.jsii.tests.calculator.VariadicMethod;
+import software.amazon.jsii.tests.calculator.*;
```
Comment (eladb) [inline packages/jsii-java-runtime-test/project/src/test/java/software/amazon/jsii/testing/ComplianceTest.java]: yeah!

Comment (RomainMuller) [reply packages/jsii-java-runtime-test/project/src/test/java/software/amazon/jsii/testing/ComplianceTest.java]: That was done automagically by my IDE... All hail to our IDE overlords!
